### ISSUE TITLE
请问目前时需要用flutter什么版本的sdk运行？3.22.3可以吗？

### ISSUE THREAD

**Issue by SheepYang1993** [wilinz/aimigo#1]

**Comment by wilinz** [comment]
能编译就行，版本在 [https://github.com/wilinz/aimigo/blob/main/.github/workflows/release_android.yaml](https://github.com/wilinz/aimigo/blob/main/.github/workflows/release_android.yaml) 里面有
```yaml
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.22.2
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
```
